trigger:
  tags:
    include:
      - 1.*

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: npm

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: ">=14.0.0"
      checkLatest: true

  - task: CmdLine@2
    inputs:
      script: |
        curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
        pnpm install --global gulp-cli
        pnpm install
        pnpm run build
        echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > .npmrc
        cd dist
        npm shrinkwrap
        npm config set userconfig=$(Build.SourcesDirectory)/.npmrc
        npm publish

  - task: Npm@1
    inputs:
      command: "publish"
      workingDir: "dist"
