trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github

steps:
- checkout: self
  fetchDepth: 1
  lfs: true

- task: UseNode@1
  inputs:
    version: '12.x'
    checkLatest: true

- task: CmdLine@2
  inputs:
    script: |
      sudo timedatectl set-timezone Asia/Shanghai
      npm install pnpm -g
      pnpm install
      pnpm run build
      cd dist
      touch .nojekyll
      git config --global user.email "$(EMAIL)"
      git config --global user.name "$(USER)"
      git init
      git add .
      git commit -m update
      git push --force --quiet https://$(TOKEN)@github.com/u2sb/hexo-tag-mmedia master:gh-pages
