trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github
- group: search

steps:
- checkout: self
  fetchDepth: 1
  submodules: true

- task: UseNode@1
  inputs:
    version: "12.x"
    
- task: CmdLine@2
  inputs:
    script: |
      curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      pnpm add -g hexo-cli
      pnpm install
      sed -i 's/your_token/$(BAIDU_PUSH_TOKEN)/g' ./_config.yml
      hexo clean
      hexo g
      
      #GitHub Page
      cd public
      touch .nojekyll
      git config --global user.email "$(EMAIL)"
      git config --global user.name "$(USER)"
      git init
      git add .
      git commit -m update
      git push --force --quiet https://$(TOKEN)@github.com/u2sb/hexo-tag-mmedia.git master:gh-pages
